
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-reader-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default
    namespace: monitoring  # The namespace where Prometheus is running
roleRef:
  kind: Role
  name: prometheus-reader
  apiGroup: rbac.authorization.k8s.io
