name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Images
        uses: docker/build-push-action@v6
        with:
          context: ./
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.run_id }}
            ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ github.run_id }}

      - name: Update Deployment Files
        run: |
          $newTagBackend = '${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.run_id }}'
          $newTagFrontend = '${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ github.run_id }}'
          (Get-Content k8s/backend-deploy.yml) -replace 'image: .*', "image: $newTagBackend" | Set-Content k8s/backend-deploy.yml
          (Get-Content k8s/frontend-deploy.yml) -replace 'image: .*', "image: $newTagFrontend" | Set-Content k8s/frontend-deploy.yml

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/backend-deploy.yml
          kubectl apply -f k8s/backend-svc.yml
          kubectl apply -f k8s/frontend-deploy.yml
          kubectl apply -f k8s/frontend-svc.yml
          kubectl apply -f k8s/mongo-deploy.yml
          kubectl apply -f k8s/mongo-svc.yml
          kubectl apply -f k8s/secrets.yml


