name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set PowerShell Execution Policy for the Session
        run: |
          Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push action
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{github.run_id}}


      - name: Build and Push action
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{github.run_id}}


     # - name: Update Backend Deployment File
      #  run: |
       #   $newTagBackend = '${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.run_id }}'
        #  (Get-Content backend-deploy.yml) -replace 'image: .*', "image: $newTagBackend" | Set-Content backend-deploy.yml

    #  - name: Update Frontend Deployment File
     #   run: |
      #    $newTagFrontend = '${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ github.run_id }}'
       #   (Get-Content frontend-deploy.yml) -replace 'image: .*', "image: $newTagFrontend" | Set-Content frontend-deploy.yml



      - name: Deploy Backend to Kubernetes
        run: |
          kubectl apply -f backend-deploy.yml
          kubectl apply -f backend-svc.yml

      - name: Deploy Frontend to Kubernetes
        run: |
          kubectl apply -f frontend-deploy.yml
          kubectl apply -f frontend-svc.yml

